import type { ShipmentWorkflowSnapshot } from "@/lib/logistics/types";

export type LogisticsShipment = {
  id: string;
  orderId: string;
  parentShipmentId?: string | null;
  logisticsBatchId?: string | null;
  orderNumber: string;
  customerName: string;
  customerPhone?: string;
  customerEmail?: string;
  customerWhatsApp?: string;
  product?: string;
  freightPartner: string;
  freightPartnerId?: string | null;
  mode: string;
  deliveryScope?: "FULL" | "PARTIAL" | "MULTI_LEG" | "SPLIT_DELIVERY";
  shipmentRole?: "PRIMARY" | "LEG" | "PARTIAL";
  splitGroupKey?: string | null;
  segmentIndex?: number | null;
  segmentLabel?: string | null;
  origin?: string | null;
  destination?: string | null;
  trackingNumber?: string;
  trackingProvider?: string | null;
  trackingStatus?: string | null;
  trackingUrl?: string | null;
  lastTrackingSyncAt?: string | Date | null;
  status: string;
  daysInStatus: number;
  riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  riskReasons: string[];
  cost: number;
  marginPercent: number;
  slaDueAt?: string | Date | null;
  daysLate?: number;
  slaStatus?: "SLA_WARNING" | "SLA_BREACH" | null;
  weight?: number | null;
  volume?: number | null;
  lastUpdateAt?: string | Date;
  lastLocation?: string | null;
  estimatedArrival?: string | Date | null;
  estimatedDeparture?: string | Date | null;
  trackingEvents: {
    id: string;
    event: string;
    location?: string | null;
    description?: string | null;
    occurredAt: string | Date;
  }[];
  customsClearance?: any;
  consolidationBatchId?: string | null;
  groupageBatchId?: string | null;
  batchSummary?: {
    id: string;
    label: string;
    type: "GROUPAGE" | "CONSOLIDATION";
    status: string;
  } | null;
  parentShipment?: {
    id: string;
    status: string;
    orderNumber?: string | null;
  } | null;
  childShipmentCount?: number;
  apiConnected?: boolean;
  aiInsight?: {
    predictedArrival?: string | Date | null;
    predictedDelayDays?: number | null;
    riskScore?: number | null;
    riskLevel?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL" | null;
    factors?: any[];
    calculatedAt?: string | Date | null;
  };
  costLines?: {
    id: string;
    type: string;
    amount: number;
    currency: string;
    notes?: string | null;
  }[];
  incidents?: {
    id: string;
    type: string;
    severity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
    status: "OPEN" | "INVESTIGATING" | "RESOLVED" | "ESCALATED" | "CLOSED";
    description: string;
    resolution?: string | null;
    amount?: number | null;
    currency?: string | null;
    createdAt?: string | Date;
    resolvedAt?: string | Date | null;
  }[];
  disputes?: {
    id: string;
    type: string;
    status: string;
    description: string;
    resolution?: string | null;
    amount?: number | null;
    currency?: string | null;
    createdAt?: string | Date;
    resolvedAt?: string | Date | null;
  }[];
  workflow?: ShipmentWorkflowSnapshot;
};

export type LogisticsDashboardData = {
  shipments: LogisticsShipment[];
  shipmentsInProgress: LogisticsShipment[];
  statusCounts: Record<string, number>;
  modeCounts: Record<string, number>;
  ports: { origins: { port: string; count: number }[]; destinations: { port: string; count: number }[] };
  customsIssues: {
    id: string;
    shipmentId: string;
    orderId: string;
    customerName: string;
    country: string;
    reason: string;
    amountNeeded: number;
    whoMustAct: string;
    daysBlocked: number;
    priority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
    documents: any[];
    documentsCount: number;
  }[];
  freightPartners: {
    id: string;
    name: string;
    type: string;
    country: string;
    city?: string;
    rating: number;
    contactName?: string;
    phone?: string;
    whatsapp?: string;
    email?: string;
    wechat?: string;
    website?: string;
    address?: string;
    contactsJson?: Record<string, unknown>;
    serviceProfileJson?: Record<string, unknown>;
    notes?: string;
    modes: string[];
    apiConnected: boolean;
    avgDeliveryDays: number;
    lateShipmentPercent: number;
    costPerKg: number;
    costPerCbm: number;
    reliabilityScore: number;
    activeShipments: number;
    shipmentsCount: number;
    onTimeRate: number;
    lastShipmentAt?: string | Date | null;
  }[];
  consolidationBatches: {
    id: string;
    batchNumber: string;
    status: string;
    notes?: string | null;
    updatedAt: string | Date;
    shipmentsCount: number;
    modes: string[];
    destinations: string[];
  }[];
  consolidationSuggestions: {
    destination: string;
    mode: string;
    shipments: LogisticsShipment[];
    totalWeight: number;
    totalVolume: number;
  }[];
  aiAlerts: {
    id: string;
    type: string;
    title: string;
    description: string;
    orderId: string;
    severity: "LOW" | "MEDIUM" | "HIGH";
    action: string;
    timestamp: string;
  }[];
  analytics: {
    statusChart: { status: string; count: number }[];
    modeChart: { mode: string; count: number }[];
    monthlyCounts: { month: string; count: number }[];
    transitByModeChart: { mode: string; avgDays: number }[];
  };
  kpis: {
    onTimeRate: number;
    avgTransitDays: number;
    costPerKg: number;
    inProgressCount: number;
    trackingCoverage?: number;
    customsBacklog?: number;
    lateShipments?: number;
  };
};
