import type {
  AgentToolDefinition,
  HorionAgentDefinition,
  HorionAgentId,
} from "@/lib/agents/types";

export const AGENT_TOOL_CATALOG: AgentToolDefinition[] = [
  {
    id: "whatsapp.read_conversations",
    label: "Lire conversations WhatsApp",
    module: "whatsapp",
    description: "Consulter les conversations, intents et signaux entrants.",
    risk: "read",
  },
  {
    id: "whatsapp.reply_customer",
    label: "Repondre au client",
    module: "whatsapp",
    description: "Envoyer des reponses client selon les politiques Horion.",
    risk: "write",
  },
  {
    id: "crm.qualify_intent",
    label: "Qualifier intention CRM",
    module: "crm",
    description: "Transformer une intention en lead, contact ou opportunite.",
    risk: "write",
  },
  {
    id: "crm.update_contact",
    label: "Mettre a jour contact CRM",
    module: "crm",
    description: "Mettre a jour les donnees client, tags et proprietaires.",
    risk: "write",
  },
  {
    id: "crm.segment_audience",
    label: "Segmenter audience",
    module: "crm",
    description: "Construire des cohortes marketing et commerciales.",
    risk: "write",
  },
  {
    id: "orders.open_minor_dispute",
    label: "Ouvrir litige mineur",
    module: "orders",
    description: "Creer un litige mineur ou une tache de resolution client.",
    risk: "write",
  },
  {
    id: "marketing.prepare_campaign",
    label: "Preparer campagne",
    module: "marketing",
    description: "Assembler brief, audience, canal et contenu de campagne.",
    risk: "write",
  },
  {
    id: "marketing.publish_content",
    label: "Publier contenu",
    module: "marketing",
    description: "Pousser un contenu valide vers les canaux marketing/community.",
    risk: "write",
  },
  {
    id: "marketing.refresh_market_watch",
    label: "Mettre a jour la veille",
    module: "marketing",
    description: "Rafraichir les signaux de marche et analyses competitives.",
    risk: "write",
  },
  {
    id: "finance.read_cash_position",
    label: "Lire position cash",
    module: "finance",
    description: "Consulter cash, runway, flux et anomalies de tresorerie.",
    risk: "read",
  },
  {
    id: "finance.prepare_approval",
    label: "Preparer approval finance",
    module: "finance",
    description: "Monter une demande d'approbation ou une recommandation controlee.",
    risk: "approval",
  },
  {
    id: "finance.reconcile_transactions",
    label: "Rapprocher transactions",
    module: "finance",
    description: "Proposer du matching et signaler les ecarts bancaires.",
    risk: "write",
  },
  {
    id: "finance.prepare_invoice",
    label: "Preparer facture",
    module: "finance",
    description: "Assembler facture, echeancier et relances associees.",
    risk: "write",
  },
  {
    id: "sourcing.create_indicative_quote",
    label: "Creer devis indicatif",
    module: "sourcing",
    description: "Produire un cadrage prix/delais avant sourcing profond.",
    risk: "write",
  },
  {
    id: "sourcing.create_deep_case",
    label: "Creer cas sourcing profond",
    module: "sourcing",
    description: "Ouvrir et structurer un cas de sourcing profond.",
    risk: "write",
  },
  {
    id: "sourcing.record_supplier_offer",
    label: "Enregistrer offre fournisseur",
    module: "sourcing",
    description: "Ajouter une offre fournisseur ou une comparaison dans le pipeline.",
    risk: "write",
  },
  {
    id: "catalog.curate_supplier_product",
    label: "Curer le catalogue",
    module: "catalog",
    description: "Mettre a jour les produits/fournisseurs fiables du catalogue epure.",
    risk: "write",
  },
  {
    id: "sourcing.prepare_negotiation",
    label: "Preparer negotiation",
    module: "sourcing",
    description: "Constituer argumentaire, comparatif et garde-fous de negociation.",
    risk: "write",
  },
  {
    id: "logistics.track_shipments",
    label: "Suivre expeditions",
    module: "logistics",
    description: "Recuperer ETA, incidents et jalons d'expedition.",
    risk: "write",
  },
  {
    id: "logistics.raise_incident",
    label: "Ouvrir incident logistique",
    module: "logistics",
    description: "Declarer incident, escalation ou blocage shipment.",
    risk: "write",
  },
  {
    id: "qc.schedule_inspection",
    label: "Planifier inspection QC",
    module: "qc",
    description: "Declencher inspection virtuelle, physique ou extreme.",
    risk: "write",
  },
  {
    id: "qc.publish_report",
    label: "Publier rapport QC",
    module: "qc",
    description: "Publier resultat QC et signaux pass/warn/fail.",
    risk: "write",
  },
  {
    id: "logistics.block_release",
    label: "Bloquer liberation shipment",
    module: "logistics",
    description: "Bloquer la poursuite logistique suite a risque critique ou QC fail.",
    risk: "approval",
  },
  {
    id: "tasks.create_follow_up",
    label: "Creer tache de suivi",
    module: "tasks",
    description: "Creer une tache ou un handoff vers humain ou autre agent.",
    risk: "write",
  },
  {
    id: "tasks.delegate_to_agent",
    label: "Deleguer a un agent",
    module: "tasks",
    description: "Transmettre un contexte et une execution a un agent pair.",
    risk: "write",
  },
];

export const AGENT_TOOL_MAP = Object.fromEntries(
  AGENT_TOOL_CATALOG.map((tool) => [tool.id, tool])
) as Record<string, AgentToolDefinition>;

export const HORION_AGENT_DEFINITIONS: Record<HorionAgentId, HorionAgentDefinition> = {
  customer_service: {
    id: "customer_service",
    name: "Agent Service Client",
    persona: "Frontline Care",
    summary: "Traite les conversations client, qualifie les intentions et gere les litiges mineurs.",
    modules: ["whatsapp", "crm", "orders", "tasks"],
    customerFacing: true,
    autonomy: "supervised",
    defaultTools: [
      "whatsapp.read_conversations",
      "whatsapp.reply_customer",
      "crm.qualify_intent",
      "crm.update_contact",
      "orders.open_minor_dispute",
      "tasks.create_follow_up",
    ],
    handoffTargets: ["sourcing", "logistics_qc", "finance"],
    escalationSummary: "Escalade vers sourcing, logistique/QC ou finance selon le risque.",
  },
  community_manager: {
    id: "community_manager",
    name: "Agent Community Manager",
    persona: "Community Operations",
    summary: "Anime les groupes, prepare les publications et remonte les signaux communautaires.",
    modules: ["whatsapp", "marketing", "crm", "tasks"],
    customerFacing: true,
    autonomy: "supervised",
    defaultTools: [
      "whatsapp.read_conversations",
      "marketing.prepare_campaign",
      "marketing.publish_content",
      "crm.segment_audience",
      "tasks.create_follow_up",
    ],
    handoffTargets: ["marketing", "customer_service"],
    escalationSummary: "Escalade vers marketing pour validation et vers service client pour cas individuels.",
  },
  marketing: {
    id: "marketing",
    name: "Agent Marketing",
    persona: "Growth Analyst",
    summary: "Pilote la veille, le contenu, les campagnes et la lecture des performances.",
    modules: ["marketing", "crm", "tasks"],
    customerFacing: false,
    autonomy: "supervised",
    defaultTools: [
      "marketing.prepare_campaign",
      "marketing.publish_content",
      "marketing.refresh_market_watch",
      "crm.segment_audience",
      "tasks.create_follow_up",
    ],
    handoffTargets: ["community_manager", "finance", "customer_service"],
    escalationSummary: "Escalade budget vers finance et diffusion vers community manager.",
  },
  finance: {
    id: "finance",
    name: "Agent Finance",
    persona: "Control Tower",
    summary: "Assiste la comptabilite, la tresorerie, les approvals et les anomalies financieres.",
    modules: ["finance", "orders", "tasks"],
    customerFacing: false,
    autonomy: "guarded_write",
    defaultTools: [
      "finance.read_cash_position",
      "finance.prepare_approval",
      "finance.reconcile_transactions",
      "finance.prepare_invoice",
      "tasks.create_follow_up",
    ],
    handoffTargets: ["customer_service", "sourcing", "logistics_qc"],
    escalationSummary: "Toute ecriture critique ou blocage cash requiert validation humaine.",
  },
  sourcing: {
    id: "sourcing",
    name: "Agent Sourcing",
    persona: "Procurement Copilot",
    summary: "Produit les devis indicatifs, ouvre les cas profonds et veille sur le catalogue epure.",
    modules: ["sourcing", "catalog", "crm", "tasks"],
    customerFacing: false,
    autonomy: "guarded_write",
    defaultTools: [
      "sourcing.create_indicative_quote",
      "sourcing.create_deep_case",
      "sourcing.record_supplier_offer",
      "catalog.curate_supplier_product",
      "sourcing.prepare_negotiation",
      "tasks.create_follow_up",
    ],
    handoffTargets: ["finance", "logistics_qc", "customer_service"],
    escalationSummary: "Escalade vers finance pour validations et vers logistique/QC pour produits sensibles.",
  },
  logistics_qc: {
    id: "logistics_qc",
    name: "Agent Logistique & QC",
    persona: "Fulfillment Guard",
    summary: "Suit les expeditions, incidents et inspections QC jusqu'au blocage si necessaire.",
    modules: ["logistics", "qc", "orders", "tasks"],
    customerFacing: false,
    autonomy: "guarded_write",
    defaultTools: [
      "logistics.track_shipments",
      "logistics.raise_incident",
      "qc.schedule_inspection",
      "qc.publish_report",
      "logistics.block_release",
      "tasks.create_follow_up",
    ],
    handoffTargets: ["customer_service", "sourcing", "finance"],
    escalationSummary: "Escalade immediate vers humain si QC fail, incident critique ou blocage shipment.",
  },
};

export const HORION_AGENT_IDS = Object.keys(HORION_AGENT_DEFINITIONS) as HorionAgentId[];
