module.exports = {
  apps: [
    {
      name: "horion-prod",
      cwd: "/opt/horion/prod",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3000",
      interpreter: "node",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      time: true,
      max_memory_restart: "1G",
      env: {
        NODE_ENV: "production",
        PORT: "3000",
        HOSTNAME: "0.0.0.0",
      },
      out_file: "/var/log/horion/pm2/prod-out.log",
      error_file: "/var/log/horion/pm2/prod-error.log",
      merge_logs: true,
    },
    {
      name: "horion-staging",
      cwd: "/opt/horion/staging",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3001",
      interpreter: "node",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      time: true,
      max_memory_restart: "1G",
      env: {
        NODE_ENV: "production",
        PORT: "3001",
        HOSTNAME: "0.0.0.0",
      },
      out_file: "/var/log/horion/pm2/staging-out.log",
      error_file: "/var/log/horion/pm2/staging-error.log",
      merge_logs: true,
    },
  ],
};
